#!/usr/bin/python3
"""
    BaseModle Module
"""

import datetime
import uuid


class BaseModel():
    """
    BaseModel Class

    Public instance attributes:
        id (str)        : unique ID for instances generated by uuid4.
        created_at (ISOFORMAT): Date&Time when an instance is created.
        updated_at (ISOFORMAT): Date&Time when an instance is last modified.
    """

    id = str(uuid.uuid4())
    created_at = 
    updated_at =

    def save(self):
        """
        Updates the public instance attribute updated_at,
        with the current datetime.
        """
        pass
    def to_dict(self):
        """
        Returns a dictionary containing all keys/values
        of __dict__ of the instance.
        """
        pass
