#!/usr/bin/python3
"""
    BaseModle Module
"""

from datetime import datetime
import uuid


class BaseModel():
    """
    BaseModel Class
    """

    def __init__(self):
        """
        Initializing instances.

        Attributes:
        id (str)             : unique ID for instances generated by uuid4.
        created_at (datetime): Date&Time when an instance is created.
        updated_at (datetime): Date&Time when an instance is last modified.
        """
        self.id = str(uuid.uuid4())
        self.created_at = datetime.today()
        self.updated_at = datetime.today()

    def __str__(self):
        """
        str
        """
        return "[{}] ({}) {}".format(self.__class__.__name__, self.id, self.__dict__)

    def save(self):
        """
        Updates the public instance attribute updated_at,
        with the current datetime.
        """
        self.updated_at = datetime.today()

    def to_dict(self):
        """
        Returns a dictionary containing all __dict__ keys/values
        of the instance.
        """
        obj_dict = self.__dict__.copy()
        obj_dict["created_at"] = self.created_at.isoformat()
        obj_dict["updated_at"] = self.updated_at.isoformat()
        obj_dict ["__class__"] = self.__class__.__name__
        return obj_dict
